### ISSUE TITLE
Executable Demo

### ISSUE THREAD

**Issue by amullins83** [skeeto/igloojs#1]
I love the idea of this library, but I'm having trouble using the demo code from the readme in an actual application. What is the recommended way to load vertices and textures? A minimal example that draws a static object (perhaps an igloo model?) would be nice.

**Comment by skeeto** [comment]
Turns out the demo snippet in the README was slightly out of date. I
pushed an update for it (e784b56). I also just added a minimal demo in
the demo/ directory to get you started.

Just in case you weren't aware, almost all my WebGL demos use Igloo, so
you can inspect those as well:
- http://nullprogram.com/toys/

But note that a couple of them use an older version of Igloo, with a
slightly older (read: crappier) Igloo API.

**Comment by amullins83** [comment]
Thanks! It took me a while to realize the awesome nullprogram particle physics demo that led me here was yours. I'm a bit slow, but I'll get there.

**Comment by skeeto** [comment]
> What is the recommended way to load vertices and textures?

Forgot to respond to this question. For textures, you can load DOM images directly via Igloo, like in the demo. For vertices, you can create a buffer from a plain old JavaScript array via Igloo, just like the "quad" property in the demo.

**Comment by amullins83** [comment]
Ok. I guess there was something wrong with the image I was trying to use, then. I generated a DDS in Visual Studio with 128x128 dimensions and set the format to RGBA to match the default format in Igloo, but it kept throwing the "bad texture" error. I finally got the quad to draw by changing my shader to just set `gl_FragColor = tint`. Got a nice big red box. I'm proud of it.
